apiVersion: apps/v1
kind: Deployment
metadata:
  name: husker-app-2020
  namespace: vcs-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: husker-app-2020
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: husker-app-2020
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - husker-app-2020
                topologyKey: kubernetes.io/hostname
      containers:
        - name: husker-app-2020
          image: johntcronin/huskerapp2020:1.6
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.2"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          env:
            - name: RUNTIME_ENV
              value: ITG
            - name: http_proxy
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: husker-app-2020
  namespace: vcs-lab
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: husker-app-2020
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: husker-app-2020
  namespace: vcs-lab
spec:
  virtualhost:
    fqdn: husker-app-2020.mutualofomaha.com
    tls:
      secretName: tlswcmoo
  routes:
    - conditions:
      - prefix: /
      services:
        - name: husker-app-2020
          port: 80
          weight: 100